### ISSUE TITLE
Failure to load DB contents

### ISSUE THREAD

**Issue by duncdrum** [wolfgangmm/atom-existdb#2]
OSX 10.11.4; Atom 1.7.0; exist 2.2;  atom-exist 0.2.0
I followed the install instruction for my local copy of exist. After setting my password, I saw the prompt in Atom to install Server side support scripts for the Atom editor package which I did.  Dashboard says they are installed and there is nothing in the exist-log that suggest a problem with the library. 

Username, PW, and URI to local install are triple checked and are all correct. I restarted/reinstalled the package in atom and exist multiple times

Yet, Toggle Database View only results in. 
![screenshot 2016-04-14 13 50 50](https://cloud.githubusercontent.com/assets/6205362/14527102/f6cec4c6-0247-11e6-8d54-45e20000c9f7.png)

Should this work with 2.2, is there a way to learn more about the bad request?

Thanks for the package Wolfgang this will be great.

**Comment by joewiz** [comment]
The eXist support app required for the Atom package definitely won't work in 2.2, at least as currently written. Queries like https://github.com/wolfgangmm/atom-editor-support/blob/master/atom-autocomplete.xql use XQuery 3.1. I can think of two ways to help:

- The README.md file mention should eXist version requirements.
- The support package should declare its version dependencies so that when https://github.com/wolfgangmm/atom-existdb/blob/8f1e1e10dc991d0127a0d1b182a0b4c0e3aec52a/lib/existdb-tree-view.coffee#L440 has the eXist instance fire the request to download the package from the public repo, the repo will warn about the installation.

**Comment by duncdrum** [comment]
Thanks for clarifying Joe. I figured that it was a 3.0 thing. I agree that both dashboard and atom readme should include a min version warning. 
Looking forward to 3.0 ....just not to migrating :-(
